### ISSUE TITLE
Create CHICKENLOVERS

### ISSUE THREAD

**Issue by friedchickenrob** [the-pollos-hermanos/creamy-mash#7]
Let's create a file to know which developers like chicken!

**Comment by apricotfriendly** [comment]
@quest-bot-dev stash 100

**Comment by apricotfriendly** [comment]
@quest-bot-dev stash 100

**Comment by apricotfriendly** [comment]
@quest-bot-dev stash 100

**Comment by broccolibreakfast** [comment]
@quest-bot-dev embark

**Comment by apricotfriendly** [comment]
@quest-bot-dev reward @broccolibreakfast
